### ISSUE TITLE
Compatibility using Django Grappelli

### ISSUE THREAD

**Issue by Xepe** [dizballanze/django-admin-env-notice#1]
* django-admin-env-notice version: 0.1.1
* Django version: 1.11.2
* Python version: 3.6
* Operating System: Linux

### Description
I am trying to setup django admin env notice using django grappelli

### What I Did
I installed the package and I got the following:

Everything looks good
![image](https://user-images.githubusercontent.com/2806076/27565395-4a3b3084-5a9b-11e7-8a37-bac7562aeb9d.png)

But when I scroll down I see a space in the top because the position of the header in grappelli is fixed
![image](https://user-images.githubusercontent.com/2806076/27565382-3c2a9a5c-5a9b-11e7-8d76-08682785a37c.png)

Would be great to have compatibility with grappelli.
Regards.

**Comment by radyz** [comment]
I've just uploaded a PR to fix this issue, please have a look at https://github.com/dizballanze/django-admin-env-notice/pull/2.

Basically we just need a setting to override the template selector so that when we have x,y,z admin theme setup we can hook it up however that theme works, in this case grappelli.

**Comment by dizballanze** [comment]
Hi, I've released [new version](https://pypi.python.org/pypi/django-admin-env-notice/0.1.2) on pypi with @radyz patch.
